### ISSUE TITLE
Any chance make first release?

### ISSUE THREAD

**Issue by kloczek** [OpenPrinting/foomatic-db#17]
It would be nice to make first release and tag it in git repo.

**Comment by kloczek** [comment]
Still no released version :/

**Comment by tillkamppeter** [comment]
foomatic-db is a pure data collection. It does not contain any code. Therefore we have never issued releases of it. There are daily snapshots versioned by the date, and this is what operating system distributions use.

**Comment by kloczek** [comment]
Markin g=version is not only for the code.
You can find mamy packages in typical Linux distribuytion which contains only data whd are still versioned.
Tagging allows easier tace of issues between versions.

Peally please try consider starting tagging foomatic-db repo for example one time month.
With tags it would be easier to find some issues with foomatic-db definitions.
