### ISSUE TITLE
Issue with Brother printers, 1610 series : just disappeared from the DB

### ISSUE THREAD

**Issue by Asquator** [OpenPrinting/foomatic-db#31]
In the past there were FOSS drivers for DCP-1610W and other DCP printers:
http://web.archive.org/web/20211018171313/https://openprinting.org/printers/manufacturer/Brother

Now all these Brother printers are gone. What happened? How can I download a driver for one of those models?

**Comment by ValdikSS** [comment]
I guess these were the part of the website only (the website says `User-contributed printer entry which is not yet verified and/or proofread. The printer entry is not included in the Foomatic packages yet.`), that's why they are not in the database and since the website is gone, these are too.
